name: Daily Meditation SMS

on:
  schedule:
    # Runs at 8:00 AM UTC (adjust as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  send-meditation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6 libgconf-2-4
          
      - name: Run daily meditation script
        env:
          GVOICE_EMAIL: ${{ secrets.GVOICE_EMAIL }}
          GVOICE_PASSWORD: ${{ secrets.GVOICE_PASSWORD }}
          GVOICE_NUMBER: ${{ secrets.GVOICE_NUMBER }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: |
          # Install jq for JSON processing
          sudo apt-get update && sudo apt-get install -y jq
          
          # Create config.json
          echo '{
            "gvoice": {
              "email": "'"$GVOICE_EMAIL"'",
              "password": "'"$GVOICE_PASSWORD"'"
            },
            "recipients": ["'"$RECIPIENTS"'"],
            "history_size": 7,
            "history": []
          }' > config.json
          
          # Set up virtual display
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
          
          # Run the script
          python daily_meditation.py
          
      - name: Commit and push changes
        run: |
          git add config.json
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Update meditation history [skip ci]" && \
           git push)
