name: Daily Meditation SMS

on:
  schedule:
    # Runs at 8:00 AM UTC (adjust as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  send-meditation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygooglevoice
          sudo apt-get update
          sudo apt-get install -y xvfb firefox-esr
          
      - name: Run daily meditation script
        env:
          GVOICE_EMAIL: ${{ secrets.GVOICE_EMAIL }}
          GVOICE_PASSWORD: ${{ secrets.GVOICE_PASSWORD }}
          GVOICE_NUMBER: ${{ secrets.GVOICE_NUMBER }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y jq xvfb firefox-esr
          
          # Install geckodriver
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-*.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          
          # Create config.json
          echo '{
            "gvoice": {
              "email": "'"$GVOICE_EMAIL"'",
              "password": "'"$GVOICE_PASSWORD"'",
              "phone_number": "'"$GVOICE_NUMBER"'"
            },
            "recipients": ["'"$RECIPIENTS"'"],
            "history_size": 7,
            "history": []
          }' > config.json
          
          # Set up virtual display for headless browser
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          
          # Run the script
          python daily_meditation.py
          
      - name: Commit and push changes
        run: |
          git add config.json
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Update meditation history [skip ci]" && \
           git push)
