name: Daily Meditation SMS

on:
  schedule:
    # Runs at 8:00 AM UTC (adjust as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  send-meditation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gvoice
          
      - name: Run daily meditation script
        env:
          # These secrets need to be set in your repository's settings
          GVOICE_EMAIL: ${{ secrets.GVOICE_EMAIL }}
          GVOICE_PASSWORD: ${{ secrets.GVOICE_PASSWORD }}
          GVOICE_NUMBER: ${{ secrets.GVOICE_NUMBER }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: |
          # Create config.json if it doesn't exist
          if [ ! -f config.json ]; then
            echo '{
              "gvoice": {
                "email": "'"$GVOICE_EMAIL"'",
                "password": "'"$GVOICE_PASSWORD"'",
                "phone_number": "'"$GVOICE_NUMBER"'"
              },
              "recipients": ["'"$RECIPIENTS"'"],
              "history_size": 7,
              "history": []
            }' > config.json
          else
            # Update existing config with GVoice settings
            jq --arg email "$GVOICE_EMAIL" \
               --arg pass "$GVOICE_PASSWORD" \
               --arg num "$GVOICE_NUMBER" \
               --argjson rec "[\"$RECIPIENTS\"]" '
              .gvoice = {
                email: $email,
                password: $pass,
                phone_number: $num
              } | .recipients = $rec' config.json > config.tmp && mv config.tmp config.json
          fi
          
          # Install jq if not already installed (for JSON processing)
          sudo apt-get update && sudo apt-get install -y jq
          
          # Run the script with headless browser support
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          python daily_meditation.py
          
      - name: Commit and push changes
        run: |
          git add config.json
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Update meditation history [skip ci]" && \
           git push)
